default_language_version:
    python: python3
exclude: '.*/snapshots/.*\.py'
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.10.2
    hooks:
      - id: pylint
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        exclude: (lint.py|test.py|write_path.py)