name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release Magic ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build and publish to TestPyPI
        if: ${{ secrets.TESTPYPI_ENABLED == 'true' }}
        env:
          TESTPYPI_TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $TESTPYPI_TOKEN
          poetry build
          poetry publish -r testpypi
